syntax = "proto3";
package core.api.flexibility.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";
import "google/type/date.proto";
import "google/type/datetime.proto";
import "google/api/annotations.proto";
import "google/api/httpbody.proto";
import "core/api/event/v1/event.proto";
import "core/api/tag/tag.proto";

import "core/type/metering_point.proto";
import "core/type/search.proto";
import "core/type/shared.proto";

option java_package = "com.landisgyr.gfc.api.v1.flexibility";
option java_outer_classname = "FlexibilityPb";

option go_package = "gfc/api/flexibility/v1;apiv1";

service FlexibilityService {
  rpc GetFlexibility(GetFlexibilityRequest) returns (GetFlexibilityResponse) {}
  rpc QueryFlexibilities(QueryFlexibilitiesRequest) returns (QueryFlexibilitiesResponse) {}

  rpc UploadFlexibilities(UploadCsvRequest) returns (UploadCsvResponse) {}
  rpc ConfirmUploadFlexibilities(ConfirmUploadFlexibilitiesRequest) returns (ConfirmUploadFlexibilitiesResponse) {}
}

message UploadCsvRequest {
  string metadata = 1;
  bytes content = 2;
  string filename = 3;
}

message UploadCsvResponse {
  string upload_id = 1;
  CsvSummary csv_summary = 2;
}


message CsvSummary {
  FileMetadata file_metadata = 1;
  int32 total_rows = 2;
  int32 invalid_rows = 3;
  repeated FlexibilityTypeCount flexibility_type_counts = 4;
  ErrorDetails error_details = 5;
}

message FileMetadata {
  string filename = 1;
  int64 file_size_bytes = 2;
  google.protobuf.Timestamp uploaded_at = 3;
}

message FlexibilityTypeCount {
  string flexibility_type = 1;
  int32 count = 2;
}

message ErrorDetails {
  repeated RowError errors = 3;
}

message RowError {
  int32 row_number = 1;
  string column_name = 2;
  string error_message = 3;
}

message ConfirmUploadFlexibilitiesRequest {
  string upload_id = 1;
}

message ConfirmUploadFlexibilitiesResponse {
  string upload_id = 1;
  ImportSummary import_summary = 2;
}

message ImportSummary {
  int32 total_rows = 1;
  int32 imported_rows = 2;
  int32 failed_rows = 3;
  ErrorDetails error_details = 5;
}

message GetFlexibilityRequest {
  string org_code = 1;
  string id = 2; // unique id
  google.protobuf.FieldMask field_projections = 5;
}

message GetFlexibilityResponse {
  Flexibility flexibility = 1;
}

message QueryFlexibilitiesRequest {
  repeated string org_codes = 1;
  FlexibilityQueryFilter filter = 2;
  Order order = 3;
  core.type.Pagination pagination = 4;
  google.protobuf.FieldMask field_projections = 5;
}

message QueryFlexibilitiesResponse {
  Flexibilities flexibilities = 1;
}


// Schema for Device
message Flexibility {
  string id = 1; // unique id
  string name = 3;
  string flexibility_type = 7;
}

// Filter for Device Query
message FlexibilityQueryFilter {
  repeated string flexibility_id_in = 1;
  repeated string flexibility_name_in = 2;
  repeated string flexibility_type_in = 3;
}

// Enum for Sorting Order
enum Order {
  DEVICE_ORDER_NOT_DEFINED = 0;
  DEVICE_ID_ASC = 1;
  DEVICE_ID_DESC = 2;

  DEVICE_MODEL_ASC = 3;
  DEVICE_MODEL_DESC = 4;
}

message Flexibilities {
  core.type.Meta meta = 1;
  repeated Flexibility items = 2;
}
