package com.apexsphere.flexibility_bridge_service.service;

import com.apexsphere.flexibility_bridge_service.model.MessagePayload;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Service
public class MessageProducerService {
    
    private static final Logger log = LoggerFactory.getLogger(MessageProducerService.class);

    private final RabbitTemplate rabbitTemplate;

    // Inject the Exchange name
    @Value("${messaging.rabbitmq.exchange}")
    private String exchange;

    // Inject the Routing Key for the connector request queue
    @Value("${messaging.rabbitmq.request-outbound-routing-key}")
    private String requestOutboundRoutingKey;

    public MessageProducerService(RabbitTemplate rabbitTemplate) {
        this.rabbitTemplate = rabbitTemplate;
    }

    /**
     * Publishes the request payload (including the generated record ID) 
     * to the Connector service's request queue.
     * @param payload The original message payload.
     * @param recordId The unique ID generated by the Storage Service for tracking.
     */
    public void sendRequestToConnector(MessagePayload payload, String recordId) {
        // 1. Set the generated recordId on the payload object for traceability
        payload.setRecordId(recordId); 

        // 2. Logging the full payload object before sending (requires DEBUG logging level)
        log.info("📄 Final payload being sent to connector queue: {}", payload);

        // 3. Publish the updated payload
        rabbitTemplate.convertAndSend(exchange, requestOutboundRoutingKey, payload);
        
        log.info("➡️ Published request ID: {} for Sensor ID: {} using key: {}", 
                  recordId, payload.getSensorId(), requestOutboundRoutingKey);
    }
}