server.port=${SERVER_PORT:9081}

keycloak.realm=${KEYCLOAK_REALM:master}
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080/}
keycloak.resource=${KEYCLOAK_RESOURCE:sensor-service}
keycloak.public-client=${KEYCLOAK_PUBLIC_CLIENT:true}
keycloak.bearer-only=${KEYCLOAK_BEARER_ONLY:true}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI:http://localhost:8080/realms/master}

# Kafka configuration
spring.kafka.producer.bootstrap-servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
# The line below was commented out, ensure it's either removed or remains commented out if you used it as a reference
# spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
kafka.topic.task-registration=${KAFKA_TASK_REG_TOPIC:task-topic}


# MongoDB configuration
spring.data.mongodb.host=${MONGO_HOST:localhost}
spring.data.mongodb.port=${MONGO_PORT:27017}
spring.data.mongodb.database=taskregistration
spring.data.mongodb.username=${MONGO_USERNAME:root}
spring.data.mongodb.password=${MONGO_PASSWORD:root123}
spring.data.mongodb.authentication-database=admin

logging.level.root=INFO