command:
  name: command-orchestration
  replicas: 1
  image: sbhrwldocker/command-orchestration:latest
  containerPort: 9081
  servicePort: 8081
  nodePort: 30081

task:
  name: task-orchestration
  replicas: 1
  image: sbhrwldocker/task-orchestration:latest
  containerPort: 9082
  servicePort: 8082
  nodePort: 30082

env:
  MONGO_HOST: host.docker.internal
  MONGO_PORT: "27017"
  SPRING_DATA_MONGODB_USERNAME: root
  SPRING_DATA_MONGODB_PASSWORD: root123
  SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
  SPRING_DATA_MONGODB_DATABASE: commandorchestrator
  KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:29092


commandOrchestration:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75

taskOrchestration:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
