application:
  name: flexibility-bridge

messaging:
  dapr:
    pubsub-name: ${DAPR_PUBSUB_NAME:rabbitmq-pubsub}
    request-topic: ${DAPR_REQUEST_TOPIC:flexibility-hub.request}
    connector-request-topic: ${DAPR_CONNECTOR_REQUEST_TOPIC:connector.request}
    connector-response-topic: ${DAPR_CONNECTOR_RESPONSE_TOPIC:connector.response}
    hub-response-topic: ${DAPR_HUB_RESPONSE_TOPIC:flexibility-hub.response}

logging:
  level:
    com.apexsphere.flexibility_bridge: DEBUG
    io.grpc: ERROR

grpc:
  client:
    storage-service:
      host: ${STORAGE_SERVICE_HOST:localhost}
      port: ${STORAGE_SERVICE_PORT:9090}
