version: '3.8'
services:
  # HES Simulator Service
  hes-simulator:
    build: . # Uses the Dockerfile in the current directory
    image: hes-simulator:latest
    container_name: hes-simulator
    environment:
      # Overrides the 'localhost' default in application.yml for container networking
      - SPRING_RABBITMQ_HOST=rabbitmq 
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
