apiVersion: v1
kind: Service
metadata:
  name: {{ include "hub-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hub-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.hubService.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "hub-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http-port
      protocol: TCP
      port: {{ .Values.hubService.service.httpPort }}
      targetPort: {{ .Values.hubService.service.httpTargetPort }}
    - name: grpc-port
      protocol: TCP
      port: {{ .Values.hubService.service.grpcPort }}
      targetPort: {{ .Values.hubService.service.grpcTargetPort }}
