apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingestion-grpc-service.fullname" . }}
  labels:
    {{- include "ingestion-grpc-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ingestion-grpc-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ingestion-grpc-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ingestion-grpc-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: SPRING_APPLICATION_NAME
              value: {{ .Values.env.springApplicationName | quote }}
            - name: SERVER_PORT
              value: {{ .Values.service.targetPort | quote }}
            - name: ACTIVEMQ_BROKER_URL
              value: {{ .Values.env.activeMQBrokerUrl | quote }}
            - name: ACTIVEMQ_QUEUE_NAME
              value: {{ .Values.env.activeMQQueueName | quote }}
            - name: ACTIVEMQ_USER
              value: {{ .Values.env.activeMQUser | quote }}
            - name: ACTIVEMQ_PASSWORD
              value: {{ .Values.env.activeMQPassword | quote }}
            - name: GRPC_HUB_HOST
              value: {{ .Values.env.grpcHubHost | quote }}
            - name: GRPC_HUB_PORT
              value: {{ .Values.env.grpcHubPort | quote }}
            - name: LOGGING_LEVEL_APP
              value: {{ .Values.env.loggingLevelApp | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
