application:
  name: protocol-adapter

messaging:
  dapr:
    pubsub-name: ${DAPR_PUBSUB_NAME:rabbitmq-pubsub}
    connector-request-topic: ${DAPR_CONNECTOR_REQUEST_TOPIC:connector.request}
    connector-response-topic: ${DAPR_CONNECTOR_RESPONSE_TOPIC:connector.response}
    hes-request-topic: ${DAPR_HES_REQUEST_TOPIC:hes.request}
    hes-response-topic: ${DAPR_HES_RESPONSE_TOPIC:hes.response}

logging:
  level:
    com.apexsphere.protocol-adapter-service: DEBUG
    io.grpc: DEBUG
    
grpc:
  client:
    storage-service:
      host: ${STORAGE_SERVICE_HOST:localhost}
      port: ${STORAGE_SERVICE_PORT:9090}