application:
  name: protocol-adapter

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}

messaging:
  rabbitmq:
    exchange: ${FLEX_BRIDGE_EXCHANGE:flexibility-bridge.exchange}
    request-inbound-queue: ${CONNECTOR_REQUEST_INBOUND_QUEUE:connector.request}
    request-outbound-routing-key: ${HES_REQUEST_OUTBOUND_KEY:hes.request}
    response-inbound-queue: ${HES_RESPONSE_INBOUND_QUEUE:hes.response}
    response-outbound-routing-key: ${CONNECTOR_RESPONSE_OUTBOUND_KEY:connector.response}

logging:
  level:
    org.springframework.amqp: INFO
    com.apexsphere.protocol-adapter-service: DEBUG
    io.grpc: DEBUG
    
grpc:
  client:
    storage-service:
      host: ${STORAGE_SERVICE_HOST:localhost}
      port: ${STORAGE_SERVICE_PORT:9090}