spring.application.name=${SPRING_APPLICATION_NAME:Hub service}
server.port=${SERVER_PORT:9082}
grpc.server.port=${GRPC_SERVER_PORT:50051}

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:mypassword}
spring.datasource.driver-class-name=org.postgresql.Driver
# Automatically create/update schema (good for dev)
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
# Show SQL queries in logs
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
# Format SQL queries nicely
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
# Logging configuration
logging.level.com.example.hubservice=${LOGGING_LEVEL_APP:INFO}
# Optional: show SQL queries in logs
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_HIBERNATE_SQL:DEBUG}
# Optional: show bound parameters in SQL queries
logging.level.org.hibernate.orm.jdbc.bind=${LOGGING_LEVEL_HIBERNATE_BIND:TRACE}
