spring.application.name=Hub service
server.port=${SERVER_PORT:9082}
grpc.server.port=50051

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
# Automatically create/update schema (good for dev)
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in logs
spring.jpa.show-sql=true
# Format SQL queries nicely
spring.jpa.properties.hibernate.format_sql=true
# Logging configuration
logging.level.com.example.hubservice=INFO
# Optional: show SQL queries in logs
logging.level.org.hibernate.SQL=DEBUG
# Optional: show bound parameters in SQL queries
logging.level.org.hibernate.orm.jdbc.bind=TRACE
