hpa:
  taskOrchestrator:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  commandOrchestrator:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  protocolGateway:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  sensorSimulator:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
taskOrchestrator:
  replicaCount: 1
  image:
    repository: sbhrwldocker/task-orchestrator
    tag: prod
  service:
    type: NodePort
    port: 9081
  env:
    SERVER_PORT: 9081
    KEYCLOAK_ISSUER_URI: http://10.158.22.221:8080/realms/master
    KEYCLOAK_JWK_SET_URI: http://10.158.22.221:8080/realms/master/protocol/openid-connect/certs
    KEYCLOAK_CLIENT_ID: task-service
    KEYCLOAK_PROVIDER: keycloak
    CORS_ALLOWED_ORIGINS: http://localhost:9081

commandOrchestrator:
  replicaCount: 1
  image:
    repository: sbhrwldocker/command-orchestrator
    tag: prod
  service:
    type: ClusterIP
    port: 9082
  env:
    SERVER_PORT: 9082
    COMMAND_PERSISTENCE_ENABLED: "true"

protocolGateway:
  replicaCount: 1
  image:
    repository: sbhrwldocker/protocol-gateway
    tag: prod
  env:
    SERVER_PORT: 9083
    PROTOCOL_TYPE: dlms
    SENSOR_SIMULATOR_URL: http://sensor-simulator:9084/simulate

sensorSimulator:
  replicaCount: 1
  image:
    repository: sbhrwldocker/sensor-simulator
    tag: prod
  service:
    type: ClusterIP
    port: 9084
  env:
    SERVER_PORT: 9084
    SENSOR_SIMULATOR_ENDPOINT: /simulate
