spring.application.name=Ingestion service
server.port=${SERVER_PORT:9081}
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.queue-name=registration.queue
spring.activemq.user=admin
spring.activemq.password=admin
# gRPC Hub Service Configuration
grpc.hub.host=localhost
grpc.hub.port=50051
logging.level.com.example.ingestionservice=INFO