spring.application.name=${SPRING_APPLICATION_NAME:Ingestion service}
server.port=${SERVER_PORT:9081}

spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.queue-name=${ACTIVEMQ_QUEUE_NAME:registration.queue}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}

grpc.hub.host=${GRPC_HUB_HOST:localhost}
grpc.hub.port=${GRPC_HUB_PORT:50051}

logging.level.com.example.ingestionservice=${LOGGING_LEVEL_APP:INFO}
