version: "3.8"
services:
  # Flexibility Hub Simulator Service
  flexibility-hub-simulator:
    build:
      context: .
    image: sbhrwldocker/flexibility-hub-simulator:latest
    ports:
      - "8081:8081"
    environment:
      # RabbitMQ connection details
      - SPRING_RABBITMQ_HOST=host.docker.internal
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
      # Messaging Config (Queues, Exchanges, Keys)
      - FLEX_BRIDGE_EXCHANGE=flexibility-bridge.exchange
      - HUB_REQUEST_QUEUE=flexibility-hub.request
      - HUB_REQUEST_KEY=flexibility-hub.request
      - HUB_RESPONSE_QUEUE=flexibility-hub.response
      - HUB_RESPONSE_KEY=flexibility-hub.response