apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-get-message
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-get-message
  template:
    metadata:
      labels:
        app: microservice-get-message
    spec:
      containers:
        - name: microservice-get-message
          image: sbhrwldocker/microservice-get-message:v1.0.0
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-get-message-service
spec:
  type: NodePort
  selector:
    app: microservice-get-message
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30080 # NodePort service so you can easily access the app at http://localhost:30080/message/generate
