apiVersion: v1
kind: Service
metadata:
  name: microservice-get-message-service
spec:
  type: NodePort
  selector:
    app: microservice-get-message
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30080 # NodePort service so you can easily access the app at http://localhost:30080/message/generate