global:
  # Use host.docker.internal for Docker Desktop / Kubernetes access to host
  hostIp: "10.49.149.167"
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  daprComponentsPath: "/components"

rabbitmq:
  connectionString: "amqp://admin:admin@{{ .Values.global.hostIp }}:5672"
  pubsubName: "rabbitmq-pubsub"

postgres:
  host: "10.49.149.167"
  port: "5432"
  database: "mydatabase"
  username: "myuser"
  password: "mypassword"
  stateStoreName: "postgres-statestore"

services:
  flexibilityHubSimulator:
    name: "flexibility-hub-simulator"
    image: "sbhrwldocker/flexibility-hub-simulator:dapr-latest"
    port: 8081
    nodePort: 30081
    daprRequestTopic: "flexibility-hub.request"
    daprResponseTopic: "flexibility-hub.response"
  flexibilityBridge:
    name: "flexibility-bridge"
    image: "sbhrwldocker/flexibility-bridge-service:dapr-latest"
    port: 8082
    hubRequestTopic: "flexibility-hub.request"
    connectorRequestTopic: "connector.request"
    connectorResponseTopic: "connector.response"
    hubResponseTopic: "flexibility-hub.response"
  protocolAdapter:
    name: "protocol-adapter"
    image: "sbhrwldocker/protocol-adapter-service:dapr-latest"
    port: 8083
    connectorRequestTopic: "connector.request"
    connectorResponseTopic: "connector.response"
    hesRequestTopic: "hes.request"
    hesResponseTopic: "hes.response"
  hesSimulator:
    name: "hes-simulator"
    image: "sbhrwldocker/hes-simulator:dapr-latest"
    port: 8084
    hesRequestTopic: "hes.request"
    hesResponseTopic: "hes.response"
  storageService:
    name: "storage-service"
    image: "sbhrwldocker/storage-service:dapr-latest"
    httpPort: 8086
    grpcPort: 50003
    nodePort: 30086
    daprAppId: "storage-service"
    enableStateStore: true
    dapr:
      httpPort: 3500    