apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingestion-service.fullname" . }}
  labels:
    app: {{ include "ingestion-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ingestion-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ingestion-service.name" . }}
    spec:
      containers:
        - name: ingestion-service
          image: "{{ .Values.ingestionService.image }}"
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: {{ .Values.ingestionService.service.port }}
          env:
            {{- range $key, $val := .Values.ingestionService.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
