apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingestion-service.fullname" . }}
spec:
  type: {{ .Values.ingestionService.service.type }}
  selector:
    app: {{ include "ingestion-service.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.ingestionService.service.port }}
      targetPort: {{ .Values.ingestionService.service.port }}
      nodePort: {{ .Values.ingestionService.service.nodePort }}
