apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.task.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.task.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.task.servicePort }}
      targetPort: {{ .Values.task.containerPort }}
      nodePort: {{ .Values.task.nodePort }}
