services:
  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    ports:
      - "61616:61616"   # JMS port
      - "8161:8161"     # Web console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - activemq-data:/data/activemq
      - activemq-conf:/conf

volumes:
  activemq-data:
  activemq-conf:
