apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices.fullname" . }}-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: "{{ .Values.notificationService.image.repository }}:{{ .Values.notificationService.image.tag }}"
          ports:
            - containerPort: {{ .Values.notificationService.port }}
          envFrom:
            - configMapRef:
                name: {{ include "microservices.fullname" . }}-notification-service-config
