apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: {{ .Values.notificationService.port }}
      targetPort: {{ .Values.notificationService.port }}
      name: http
