apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-hpa
  labels:
    app: notification
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification
  minReplicas: { { .Values.hpa.notification.minReplicas } }
  maxReplicas: { { .Values.hpa.notification.maxReplicas } }
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: { { .Values.hpa.notification.targetCPUUtilizationPercentage } }