apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ 'notificationService' }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-{{ 'notificationService' }}
  ports:
    - port: {{ .Values.notificationService.port }}
      targetPort: {{ .Values.notificationService.port }}
      protocol: TCP
