apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices.fullname" . }}-registration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
        - name: registration-service
          image: "{{ .Values.registrationService.image.repository }}:{{ .Values.registrationService.image.tag }}"
          ports:
            - containerPort: {{ .Values.registrationService.port }}
          env:
            {{- range $key, $value := .Values.registrationService.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: NOTIFICATION_SERVICE_URL
              value: "http://{{ include "microservices.fullname" . }}-notification-service:{{ .Values.notificationService.port }}"

