apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ 'sensorService' }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-{{ 'sensorService' }}
  ports:
    - port: {{ .Values.sensorService.port }}
      targetPort: {{ .Values.sensorService.port }}
      protocol: TCP
