apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-sensor-service
spec:
  type: NodePort
  selector:
    app: sensor-service
  ports:
    - protocol: TCP
      port: {{ .Values.sensorService.port }}
      targetPort: {{ .Values.sensorService.port }}
      name: http
      nodePort: {{ .Values.sensorService.nodePort }}
