apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices.fullname" . }}-sensor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-service
  template:
    metadata:
      labels:
        app: sensor-service
    spec:
      containers:
        - name: sensor-service
          image: "{{ .Values.sensorService.image.repository }}:{{ .Values.sensorService.image.tag }}"
          ports:
            - containerPort: {{ .Values.sensorService.port }}
          env:
            {{- range $key, $value := .Values.sensorService.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
