{{- if .Values.uiService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-uiService
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-uiService
  minReplicas: {{ .Values.uiService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.uiService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.uiService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
