[versions]
jaxb = "4.0.5"
jaxbPlugin = "1.9.1"
cxf = "4.1.3"
springBoot = "3.5.5"
springDependencyManagement = "1.1.7"

[libraries]
jaxb-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jaxb" }
jaxb-runtime = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxb" }
jaxws-api = { module = "jakarta.xml.ws:jakarta.xml.ws-api", version = "4.0.2" }

cxf-tools = { module = "org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws", version.ref = "cxf" }
cxf-jaxb = { module = "org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb", version.ref = "cxf" }

cxf-rt-frontend-jaxws = { module = "org.apache.cxf:cxf-rt-frontend-jaxws", version.ref = "cxf" }
cxf-rt-transports-http = { module = "org.apache.cxf:cxf-rt-transports-http", version.ref = "cxf" }

[plugins]
jaxb = { id = "com.github.bjornvester.xjc", version.ref = "jaxbPlugin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }