apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  selector:
    app: registration-service
  ports:
    - protocol: TCP
      port: {{ .Values.registrationService.port }}
      targetPort: {{ .Values.registrationService.port }}
  type: ClusterIP
