apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ 'registrationService' }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-{{ 'registrationService' }}
  ports:
    - port: {{ .Values.registrationService.port }}
      targetPort: {{ .Values.registrationService.port }}
      protocol: TCP
