apiVersion: v1
kind: Service
metadata:
  name: sensor-service
spec:
  selector:
    app: sensor-service
  ports:
    - protocol: TCP
      port: {{ .Values.sensorService.port }}
      targetPort: {{ .Values.sensorService.port }}
      nodePort: {{ .Values.sensorService.nodePort }}
  type: NodePort