apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
        - name: ui-service
          image: {{ .Values.uiService.image }}
          ports:
            - containerPort: {{ .Values.uiService.port }}
          env:
{% for key, value in .Values.uiService.env.items() %}
            - name: {{ key }}
              value: "{{ value }}"
{% endfor %}
