services:
  ui-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sbhrwldocker/ui-app:latest
    environment:
      - PORT=8080
      - BACKEND_URL=http://host.docker.internal:8085
    ports:
      - "8080:8080"
    restart: unless-stopped

