apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataApi.name" . }}
  labels:
    app: {{ .Values.dataApi.name }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.dataApi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dataApi.name }}
    spec:
      containers:
      - name: {{ .Values.dataApi.name }}
        image: "{{ .Values.dataApi.image }}:{{ .Values.dataApi.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.dataApi.serverPort }}
        env:
        - name: SERVER_PORT
          value: "{{ .Values.dataApi.serverPort }}"
        # External PostgreSQL Connection
        - name: DB_HOST
          value: "{{ .Values.db.host }}"
        - name: DB_PORT
          value: "{{ .Values.db.port }}"
        - name: DB_NAME
          value: {{ .Values.db.name }}
        - name: DB_USER
          value: {{ .Values.db.user }}
        - name: DB_PASS
          value: {{ .Values.db.pass }}
