apiVersion: v1
kind: Service
metadata:
  name: {{ include "flexibilityHubSimulator.name" . }}-service
  labels:
    app: {{ .Values.flexibilityHubSimulator.name }}
spec:
  # Use NodePort to allow external access for testing
  type: NodePort 
  selector:
    app: {{ .Values.flexibilityHubSimulator.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.flexibilityHubSimulator.port }}
      targetPort: {{ .Values.flexibilityHubSimulator.port }}
      nodePort: {{ .Values.flexibilityHubSimulator.nodePort }}
