apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataApi.name" . }}-service
  labels:
    app: {{ .Values.dataApi.name }}
spec:
  # Using NodePort to ensure external access for the UI App
  type: NodePort 
  selector:
    app: {{ .Values.dataApi.name }}
  ports:
    - port: {{ .Values.dataApi.serverPort }}
      targetPort: {{ .Values.dataApi.serverPort }}
      protocol: TCP
      nodePort: {{ .Values.dataApi.nodePort }}
