{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "orchestrate-hubtosensor-services.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.host | replace "." "-" }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.uiApp }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.uiApp.name }}-service
                port:
                  number: {{ .Values.uiApp.port }}
          - path: {{ .Values.ingress.paths.dataApi }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.dataApi.name }}-service
                port:
                  number: {{ .Values.dataApi.serverPort }}
          - path: {{ .Values.ingress.paths.flexibilityHubSimulator }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.flexibilityHubSimulator.name }}-service
                port:
                  number: {{ .Values.flexibilityHubSimulator.port }}
{{- end }}
