application:
  name: iec-adapter

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

messaging:
  rabbitmq:
    # --- Exchange used for all routing ---
    exchange: flexibility-bridge.exchange 
    
    # --- Request Path (Connector -> HES) ---
    request-inbound-queue: connector.request
    request-outbound-routing-key: hes.request

    # --- Response Path (HES -> Connector) ---
    response-inbound-queue: hes.response
    response-outbound-routing-key: connector.response

logging:
  level:
    org.springframework.amqp: INFO
    com.apexsphere.flexibility_bridge: DEBUG
    io.grpc: DEBUG
grpc:
  client:
    storage-service:
      host: localhost
      port: 9090