package com.apexsphere.flexibility_bridge_service.service;

import com.apexsphere.flexibility_bridge_service.model.RequestPayload;
import io.dapr.client.DaprClient;
import io.dapr.client.DaprClientBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class RequestProducerForProtocolConversionService {

    private static final Logger log = LoggerFactory.getLogger(RequestProducerForProtocolConversionService.class);

    private final DaprClient daprClient;

    @Value("${messaging.dapr.pubsub-name}")
    private String pubsubName;

    @Value("${messaging.dapr.request-topic}")
    private String requestTopic;

    public RequestProducerForProtocolConversionService() {
        // Dapr client can also be injected as a bean if you prefer
        this.daprClient = new DaprClientBuilder().build();
    }

    /**
     * Publishes the request payload (including the generated record ID)
     * to the Connector service via Dapr pub/sub.
     *
     * @param payload  The original message payload.
     * @param recordId The unique ID generated by the Storage Service for tracking.
     */
    public void sendRequestToConnector(RequestPayload payload, String recordId) {
        payload.setRecordId(recordId);

        log.info("📄 Sending payload to connector via Dapr pub/sub: {}", payload);

        try {
            // Publish the message to the configured topic via Dapr
            daprClient.publishEvent(pubsubName, requestTopic, payload).block();
            log.info("➡️ Published request ID {} for Sensor ID {} via Dapr topic '{}'", 
                     recordId, payload.getSensorId(), requestTopic);
        } catch (Exception e) {
            log.error("❌ Failed to publish request ID {} to Dapr topic {}: {}", recordId, requestTopic, e.getMessage(), e);
            throw new RuntimeException("Failed to send message via Dapr.", e);
        }
    }
}
