services:
  sensor-simulator:
    image: sbhrwldocker/sensor-simulator:latest
    container_name: sensor-simulator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9084:9084"
    environment:
      SERVER_PORT: 9084
      SENSOR_SIMULATOR_ENDPOINT: /simulate