apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-orchestrator
  template:
    metadata:
      labels:
        app: command-orchestrator
    spec:
      containers:
        - name: command-orchestrator
          image: sbhrwldocker/command-orchestrator:latest
          ports:
            - containerPort: 9082
          env:
            - name: SERVER_PORT
              value: "9082"
            - name: KAFKA_HOST
              value: "host.docker.internal"
            - name: KAFKA_PORT
              value: "29092"
            - name: KAFKA_TASK_REG_TOPIC
              value: "task-topic"
            - name: KAFKA_COMMAND_TOPIC
              value: "command-topic"
            - name: MONGO_HOST
              value: "host.docker.internal"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              value: "root123"
            - name: COMMAND_PERSISTENCE_ENABLED
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: command-orchestrator
spec:
  type: ClusterIP
  selector:
    app: command-orchestrator
  ports:
    - port: 9082
      targetPort: 9082
