version: "3.8"
services:
  # Data API Service
  data-api-service:
    build:
      context: .
    image: data-api-service:latest
    container_name: data-api-service
    ports:
      - "8085:8085"
    environment:
      # Application port
      - SERVER_PORT=8085
      
      # Database connection
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASS=mypassword