services:
  ingestion-service:
    build:
      context: .
    image: sbhrwldocker/ingestion-service:latest
    ports:
      - "9081:9081"
    environment:
      SERVER_PORT: 9081

      # ActiveMQ settings
      ACTIVEMQ_BROKER_URL: tcp://10.49.149.25:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      ACTIVEMQ_DEFAULT_DESTINATION: power-quality

      # InfluxDB settings
      INFLUXDB_HOST: http://10.49.149.25:8086
      INFLUXDB_DATABASE: power_quality
      INFLUXDB_USERNAME: admin
      INFLUXDB_PASSWORD: admin123
      INFLUXDB_SINGLE_MEASUREMENT: true
