package com.apexsphere.storage_service.service;

import com.apexsphere.storage_service.model.Record;
import io.grpc.stub.StreamObserver;
import net.devh.boot.grpc.server.service.GrpcService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * gRPC service implementation for the Storage Service using Dapr state store.
 */
@GrpcService
public class RecordGrpcServiceImpl extends RecordServiceGrpc.RecordServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(RecordGrpcServiceImpl.class);

    private final RecordService recordService;

    @Autowired
    public RecordGrpcServiceImpl(RecordService recordService) {
        this.recordService = recordService;
        log.info("RecordGrpcServiceImpl initialized.");
    }

    /**
     * Handles saving a new record (via gRPC).
     */
    @Override
    public void saveRecord(RecordRequest request, StreamObserver<RecordResponse> responseObserver) {
        log.info("[saveRecord gRPC] Incoming request: {}", request);

        try {
            Record record = new Record(
                null, // ID will be generated by service layer
                request.getSensorId(),
                request.getOperation(),
                request.getRelayNumber(),
                request.getDuration(),
                request.getStatus()
            );
            log.debug("[saveRecord gRPC] Converted gRPC request to Record model: {}", record);

            Record savedRecord = recordService.saveRecord(record);
            log.info("[saveRecord gRPC] Record saved successfully with ID: {}", savedRecord.getId());

            RecordResponse response = RecordResponse.newBuilder()
                .setSuccess(true)
                .setMessage("Record saved successfully with ID: " + savedRecord.getId())
                .setRecordId(savedRecord.getId())
                .build();

            responseObserver.onNext(response);
            responseObserver.onCompleted();
            log.info("[saveRecord gRPC] Response sent to client for record ID: {}", savedRecord.getId());

        } catch (Exception e) {
            log.error("[saveRecord gRPC] Error while saving record: {}", e.getMessage(), e);
            RecordResponse response = RecordResponse.newBuilder()
                .setSuccess(false)
                .setMessage("Failed to save record: " + e.getMessage())
                .build();
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }
    }

    /**
     * Handles updating the status of an existing record.
     */
    @Override
    public void updateRecord(RecordRequest request, StreamObserver<RecordResponse> responseObserver) {
        log.info("[updateRecord gRPC] Incoming request: {}", request);

        try {
            Record record = new Record(
                request.getRecordId(),
                request.getSensorId(),
                request.getOperation(),
                request.getRelayNumber(),
                request.getDuration(),
                request.getStatus()
            );
            log.debug("[updateRecord gRPC] Converted gRPC request to Record model: {}", record);

            Record updatedRecord = recordService.updateRecordStatus(record);
            log.info("[updateRecord gRPC] Record updated successfully: ID={}, Status={}",
                    updatedRecord.getId(), updatedRecord.getStatus());

            RecordResponse response = RecordResponse.newBuilder()
                .setSuccess(true)
                .setMessage("Record status updated to " + updatedRecord.getStatus() + " for ID: " + updatedRecord.getId())
                .setRecordId(updatedRecord.getId())
                .build();

            responseObserver.onNext(response);
            responseObserver.onCompleted();
            log.info("[updateRecord gRPC] Response sent to client for record ID: {}", updatedRecord.getId());

        } catch (Exception e) {
            log.error("[updateRecord gRPC] Error while updating record: {}", e.getMessage(), e);
            RecordResponse response = RecordResponse.newBuilder()
                .setSuccess(false)
                .setMessage("Failed to update record: " + e.getMessage())
                .build();
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }
    }
}
