application:
  name: data-api-service

server:
  port: ${SERVER_PORT:8085}

messaging:
  dapr:
    state-store-name: ${DAPR_STATESTORE_NAME:postgres-statestore}
    # Optional logical keys
    requests-index-key: ${DAPR_REQUESTS_INDEX_KEY:ControlRequest:index}

logging:
  level:
    com.apexsphere.dataapiservice: DEBUG 