apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SERVER_PORT: "9084"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: sbhrwldocker/notification-service:latest
          ports:
            - containerPort: 9084
          envFrom:
            - configMapRef:
                name: notification-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 9084
      targetPort: 9084
  type: ClusterIP