# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app-deployment
  labels:
    app: ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - name: ui-app
        image: sbhrwldocker/ui-app:latest
        ports:
        - containerPort: 8080
        env:
        # --- Application Port ---
        - name: PORT
          value: "8080"
          
        # --- Backend API Connection (Internal K8s Service) ---
        # The Pod now uses the internal ClusterIP service name of the data-api-service
        - name: BACKEND_URL
          value: "http://data-api-service:8085"
---
# Service (exposes the Deployment via a NodePort)
apiVersion: v1
kind: Service
metadata:
  name: ui-app-service
  labels:
    app: ui-app
spec:
  # NodePort allows external access (e.g., via your browser)
  type: NodePort 
  selector:
    app: ui-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
