apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microservices.fullname" . }}-notification-hpa
  labels:
    app: notification-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "microservices.fullname" . }}-notification-service
  minReplicas: {{ .Values.hpa.notification.minReplicas }}
  maxReplicas: {{ .Values.hpa.notification.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.notification.targetCPUUtilizationPercentage }}
