apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: registration-hpa
  labels:
    app: registration
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: registration
  minReplicas: {{ .Values.hpa.registration.minReplicas }}
  maxReplicas: {{ .Values.hpa.registration.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.registration.targetCPUUtilizationPercentage }}
