apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microservices.fullname" . }}-ui-hpa
  labels:
    app: ui-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "microservices.fullname" . }}-ui-service
  minReplicas: {{ .Values.hpa.ui.minReplicas }}
  maxReplicas: {{ .Values.hpa.ui.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.ui.targetCPUUtilizationPercentage }}
