version: '3.8'

services:
  sensor-service:
    build:
      context: .
    image: sensor-service:latest
    ports:
      - "9082:9082"
    environment:
      SERVER_PORT: ${SERVER_PORT:9082}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI:http://host.docker.internal:8080/realms/master}
      KEYCLOAK_CLIENT_ID: sensor-service
      KAFKA_HOST: ${KAFKA_HOST:host.docker.internal}
      KAFKA_PORT: ${KAFKA_PORT:29092}
      KAFKA_SENSOR_REG_TOPIC: sensor-registrations
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:http://host.docker.internal:9081}