version: '3.8'

services:
  sensor-service:
    build:
      context: .
    image: sensor-service:latest
    ports:
      - "9082:9082"
    environment:
      SERVER_PORT: 9082
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/master
      KEYCLOAK_CLIENT_ID: sensor-service
      KAFKA_HOST: localhost
      KAFKA_PORT: 29092
      KAFKA_SENSOR_REG_TOPIC: sensor-registrations
      CORS_ALLOWED_ORIGINS: http://localhost:9081
