version: '3.8'

services:
  sensor-service:
    image: sensor-service:latest
    container_name: sensor-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9082:9082"
    environment:
      SERVER_PORT: 9082
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/master
      KEYCLOAK_JWK_SET_URI: http://host.docker.internal:8080/realms/master/protocol/openid-connect/certs
      KEYCLOAK_CLIENT_ID: sensor-service
      KEYCLOAK_PROVIDER: keycloak
      # KEYCLOAK_CLIENT_SECRET: your-secret-if-needed
      KAFKA_HOST: host.docker.internal
      KAFKA_PORT: 29092
      KAFKA_SENSOR_REG_TOPIC: sensor-registrations
      CORS_ALLOWED_ORIGINS: http://host.docker.internal:9081
    restart: unless-stopped