# Server Configuration
server.port=9999

# JSON parsing
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.mvc.json.prefix=/api
spring.mvc.json.suffix=.json

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=taskorchestrator
spring.data.mongodb.username=root
spring.data.mongodb.password=root123
# You need to explicitly tell Spring to authenticate against the admin database.
spring.data.mongodb.authentication-database=admin

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=task-orchestrator-group
spring.kafka.consumer.auto-offset-reset=earliest
# Kafka Consumer Configuration
spring.kafka.consumer.topic=task.requested
spring.kafka.consumer.group-id=command-consumer-group
# Kafka Producer Configuration
spring.kafka.producer.topic=task.created
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Logging configuration INFO, DEBUG, ERROR
# logging.level.root=INFO
logging.level.com.org.taskorch=DEBUG