spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: itemsdb
      username: admin
      password: password
      authentication-database: admin

grpc:
  server:
    port: 9090

logging:
  level:
    org.springframework.data.mongodb: DEBUG