uiService:
  env:
    KEYCLOAK_CLIENTID: sensor-service
    KEYCLOAK_REALM: master
    KEYCLOAK_URL: http://192.168.0.103:8080/
    SENSOR_SERVICE_URL: http://192.168.0.103:30082
    SERVER_PORT: '9081'
  image: sbhrwldocker/ui-service:latest
  nodePort: 30081
  port: 9081
sensorService:
  env:
    CORS_ALLOWED_ORIGINS: http://localhost:30081,http://192.168.0.103:30081
    KAFKA_HOST: 192.168.0.103
    KAFKA_PORT: '29092'
    KAFKA_SENSOR_REG_TOPIC: sensor-registrations
    KEYCLOAK_CLIENT_ID: sensor-service
    KEYCLOAK_ISSUER_URI: http://192.168.0.103:8080/realms/master
    KEYCLOAK_JWK_SET_URI: http://192.168.0.103:8080/realms/master/protocol/openid-connect/certs
    KEYCLOAK_PROVIDER: keycloak
    SERVER_PORT: '9082'
  image: sbhrwldocker/sensor-service:latest
  nodePort: 30082
  port: 9082
registrationService:
  env:
    KAFKA_HOST: 192.168.0.103
    KAFKA_PORT: '29092'
    MONGO_HOST: 192.168.0.103
    MONGO_PASSWORD: root123
    MONGO_PORT: '27017'
    MONGO_USERNAME: root
    NOTIFICATION_SERVICE_URL: http://notification-service:9084
    SERVER_PORT: '9083'
  image: sbhrwldocker/registration-service:latest
  port: 9083
notificationService:
  config:
    SERVER_PORT: '9084'
  image: sbhrwldocker/notification-service:latest
  port: 9084
hpa:
  ui:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  sensor:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  registration:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  notification:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80