version: '3.8'

services:
  notification-service:
    image: notification-service:latest
    container_name: notification-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9084:9084"
