global:
  hostIP: 192.168.0.103

  kafka:
    port: 29092
    taskTopic: task-topic
    commandTopic: command-topic

  mongo:
    port: 27017
    username: root
    password: root123

  keycloak:
    port: 8080
    realm: master
    clientId: task-service

taskOrchestrator:
  replicaCount: 1
  image:
    repository: sbhrwldocker/task-orchestrator
    tag: staging
  service:
    type: NodePort
    port: 9081
    nodePort: 30081
  env:
    SERVER_PORT: 9081
    KEYCLOAK_ISSUER_URI: "http://{{ .Values.global.hostIP }}:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}"
    KEYCLOAK_JWK_SET_URI: "http://{{ .Values.global.hostIP }}:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}/protocol/openid-connect/certs"
    KEYCLOAK_CLIENT_ID: "{{ .Values.global.keycloak.clientId }}"
    KEYCLOAK_PROVIDER: keycloak
    CORS_ALLOWED_ORIGINS: "http://localhost:30081,http://{{ .Values.global.hostIP }}:30081"

commandOrchestrator:
  replicaCount: 1
  image:
    repository: sbhrwldocker/command-orchestrator
    tag: staging
  service:
    type: ClusterIP
    port: 9082
  env:
    SERVER_PORT: 9082
    COMMAND_PERSISTENCE_ENABLED: "true"

protocolGateway:
  replicaCount: 1
  image:
    repository: sbhrwldocker/protocol-gateway
    tag: staging
  env:
    SERVER_PORT: 9083
    PROTOCOL_TYPE: dlms
    SENSOR_SIMULATOR_URL: http://sensor-simulator:9084/simulate

sensorSimulator:
  replicaCount: 1
  image:
    repository: sbhrwldocker/sensor-simulator
    tag: staging
  service:
    type: ClusterIP
    port: 9084
  env:
    SERVER_PORT: 9084
    SENSOR_SIMULATOR_ENDPOINT: /simulate

hpa:
  taskOrchestrator:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  commandOrchestrator:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  protocolGateway:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  sensorSimulator:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80