global:
  hostIP: 192.168.0.103

  kafka:
    port: 29092
    sensorRegTopic: sensor-registrations

  mongo:
    port: 27017
    username: root
    password: root123

  keycloak:
    port: 8080
    realm: master

uiService:
  image:
    repository: sbhrwldocker/ui-service
    tag: latest
  port: 9081
  nodePort: 30081
  env:
    SERVER_PORT: '9081'
    KEYCLOAK_CLIENTID: sensor-service
    KEYCLOAK_REALM: master
    KEYCLOAK_URL: "http://192.168.0.103:8080/"
    SENSOR_SERVICE_URL: "http://192.168.0.103:30082"

sensorService:
  image:
    repository: sbhrwldocker/sensor-service
    tag: latest
  port: 9082
  nodePort: 30082
  env:
    SERVER_PORT: '9082'
    CORS_ALLOWED_ORIGINS: "http://localhost:30081,http://192.168.0.103:30081"
    KAFKA_HOST: 192.168.0.103
    KAFKA_PORT: '29092'
    KAFKA_SENSOR_REG_TOPIC: sensor-registrations
    KEYCLOAK_CLIENT_ID: sensor-service
    KEYCLOAK_ISSUER_URI: "http://192.168.0.103:8080/realms/master"
    KEYCLOAK_JWK_SET_URI: "http://192.168.0.103:8080/realms/master/protocol/openid-connect/certs"
    KEYCLOAK_PROVIDER: keycloak

registrationService:
  image:
    repository: sbhrwldocker/registration-service
    tag: latest
  port: 9083
  env:
    SERVER_PORT: '9083'
    KAFKA_HOST: 192.168.0.103
    KAFKA_PORT: '29092'
    MONGO_HOST: 192.168.0.103
    MONGO_PORT: '27017'
    MONGO_USERNAME: root
    MONGO_PASSWORD: root123
    # Put a placeholder or just literal, e.g., empty string
    NOTIFICATION_SERVICE_URL: ""

notificationService:
  image:
    repository: sbhrwldocker/notification-service
    tag: latest
  port: 9084
  config:
    SERVER_PORT: '9084'

hpa:
  ui:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  sensor:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  registration:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  notification:
    enabled: true
    maxReplicas: 5
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
