{{- if .Values.taskOrchestration.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: task-orchestration-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-orchestration
  minReplicas: {{ .Values.taskOrchestration.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.taskOrchestration.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.taskOrchestration.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
