application:
  name: hes-simulator

messaging:
  dapr:
    pubsub-name: ${DAPR_PUBSUB_NAME:rabbitmq-pubsub}
    hes-request-topic: ${DAPR_HES_REQUEST_TOPIC:hes.request}
    hes-response-topic: ${DAPR_HES_RESPONSE_TOPIC:hes.response}

logging:
  level:
    com.apexsphere.hes_simulator: DEBUG