syntax = "proto3";

// Defines the Java package and class names for the generated code.
option java_multiple_files = true;
option java_package = "com.apexsphere.storage_service.service";
option java_outer_classname = "RecordProto";

// The service definition. This will contain the RPC methods.
service RecordService {
    // Add this line to define the method for saving a record
    rpc saveRecord (RecordRequest) returns (RecordResponse);
}

// A message to represent the data you want to send and receive.
// It mirrors the fields in your Record class.
message RecordRequest {
    string sensor_id = 1;
    string operation = 2;
    int32 relay_number = 3;
    int32 duration = 4;
    int32 status = 5;
}

// A message for the response after saving a record.
message RecordResponse {
    bool success = 1;
    string message = 2;
}