application:
  name: flexibility-bridge

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

messaging:
  rabbitmq:
    # --- Exchange used for all routing ---
    exchange: flexibility-bridge.exchange 
    
    # --- Request Path (Hub -> Connector) ---
    request-inbound-queue: flexibility-hub.request
    request-outbound-routing-key: connector.request

    # --- Response Path (Connector -> Hub) ---
    response-inbound-queue: connector.response
    response-outbound-routing-key: flexibility-hub.response

logging:
  level:
    org.springframework.amqp: INFO
    com.apexsphere.flexibility_bridge: DEBUG
    io.grpc: DEBUG
grpc:
  client:
    storage-service:
      host: localhost
      port: 9090