package com.apexsphere.storage_service.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "control_requests")
public class Record {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String sensorId;
    private String operation;
    private Integer relayNumber;
    private Integer duration;
    private String status;

    public Record() {
    }

    /**
     * Constructor used for SAVE operations (ID is generated by DB).
     */
    public Record(String sensorId, String operation, Integer relayNumber, Integer duration, String status) {
        this.sensorId = sensorId;
        this.operation = operation;
        this.relayNumber = relayNumber;
        this.duration = duration;
        this.status = status;
    }
    
    /**
     * Constructor used for UPDATE operations via gRPC.
     * Accepts the ID as a String (from gRPC Request) and converts it to Long.
     */
    public Record(String id, String sensorId, String operation, Integer relayNumber, Integer duration, String status) {
        if (id != null && !id.isEmpty()) {
            // Convert the String ID received from gRPC back to Long for the JPA entity
            this.id = Long.valueOf(id);
        }
        this.sensorId = sensorId;
        this.operation = operation;
        this.relayNumber = relayNumber;
        this.duration = duration;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSensorId() {
        return sensorId;
    }

    public void setSensorId(String sensorId) {
        this.sensorId = sensorId;
    }

    public String getOperation() {
        return operation;
    }

    public void setOperation(String operation) {
        this.operation = operation;
    }

    public Integer getRelayNumber() {
        return relayNumber;
    }

    public void setRelayNumber(Integer relayNumber) {
        this.relayNumber = relayNumber;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
