services:
  command-orchestrator:
    image: sbhrwldocker/command-orchestrator:latest
    container_name: command-orchestrator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9082:9082"
    environment:
      SERVER_PORT: 9082

      # Kafka config
      KAFKA_HOST: host.docker.internal
      KAFKA_PORT: 29092
      KAFKA_TASK_REG_TOPIC: task-topic
      KAFKA_COMMAND_TOPIC: command-topic

      # MongoDB config
      MONGO_HOST: host.docker.internal
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: root123

      # Optional: command persistence toggle
      COMMAND_PERSISTENCE_ENABLED: true