apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hub-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hub-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.hubService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hub-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hub-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "hub-service.name" . }}
          image: "{{ .Values.hubService.image.repository }}:{{ .Values.hubService.image.tag }}"
          imagePullPolicy: {{ .Values.hubService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.hubService.service.httpTargetPort }}
            - containerPort: {{ .Values.hubService.service.grpcTargetPort }}
          env:
            - name: SPRING_APPLICATION_NAME
              value: {{ .Values.hubService.env.springApplicationName | quote }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.hubService.env.dbUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.hubService.env.dbUsername | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.hubService.env.dbPassword | quote }}
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: {{ .Values.hubService.env.jpaDdlAuto | quote }}
            - name: SPRING_JPA_SHOW_SQL
              value: {{ .Values.hubService.env.jpaShowSql | quote }}
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: {{ .Values.hubService.env.jpaFormatSql | quote }}
            - name: LOGGING_LEVEL_APP
              value: {{ .Values.hubService.env.loggingLevelApp | quote }}
            - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
              value: {{ .Values.hubService.env.loggingLevelHibernateSql | quote }}
            - name: LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL
              value: {{ .Values.hubService.env.loggingLevelHibernateBind | quote }}
