apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hub-service.fullname" . }}-hpa
  labels:
    app.kubernetes.io/name: {{ include "hub-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hub-service.fullname" . }}
  minReplicas: {{ .Values.hubService.hpa.minReplicas }}
  maxReplicas: {{ .Values.hubService.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hubService.hpa.targetCPUUtilizationPercentage }}
