apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingestion-grpc-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ingestion-grpc-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.ingestionGrpcService.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ingestion-grpc-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ingestionGrpcService.service.port }}
      targetPort: {{ .Values.ingestionGrpcService.env.SERVER_PORT | int }}
      protocol: TCP
      {{- if eq .Values.ingestionGrpcService.service.type "NodePort" }}
      nodePort: {{ .Values.ingestionGrpcService.service.nodePort }}
      {{- end }}
