application:
  name: flexibility-hub-simulator

server:
  port: ${SERVER_PORT:8081}

messaging:
  dapr:
    pubsub-name: ${DAPR_PUBSUB_NAME:rabbitmq-pubsub}
    hub-request-topic: ${DAPR_REQUEST_TOPIC:flexibility-hub.request}
    hub-response-topic: ${DAPR_RESPONSE_TOPIC:flexibility-hub.response}

logging:
  level:
    com.apexsphere.flexibility_hub_simulator: DEBUG