apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: command-orchestrator-hpa
  labels:
    app: command-orchestrator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: command-orchestrator
  minReplicas: {{ .Values.hpa.commandOrchestrator.minReplicas }}
  maxReplicas: {{ .Values.hpa.commandOrchestrator.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.commandOrchestrator.targetCPUUtilizationPercentage }}
