apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: protocol-gateway-hpa
  labels:
    app: protocol-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: protocol-gateway
  minReplicas: {{ .Values.hpa.protocolGateway.minReplicas }}
  maxReplicas: {{ .Values.hpa.protocolGateway.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.protocolGateway.targetCPUUtilizationPercentage }}
