apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices.fullname" . }}-protocol-gateway
spec:
  replicas: {{ .Values.protocolGateway.replicaCount }}
  selector:
    matchLabels:
      app: protocol-gateway
  template:
    metadata:
      labels:
        app: protocol-gateway
    spec:
      containers:
        - name: protocol-gateway
          image: "{{ .Values.protocolGateway.image.repository }}:{{ .Values.protocolGateway.image.tag }}"
          ports:
            - containerPort: {{ .Values.protocolGateway.env.SERVER_PORT }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.protocolGateway.env.SERVER_PORT }}"
            - name: PROTOCOL_TYPE
              value: "{{ .Values.protocolGateway.env.PROTOCOL_TYPE }}"
            - name: SENSOR_SIMULATOR_URL
              value: "{{ .Values.protocolGateway.env.SENSOR_SIMULATOR_URL }}"
