apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sensor-simulator-hpa
  labels:
    app: sensor-simulator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sensor-simulator
  minReplicas: {{ .Values.hpa.sensorSimulator.minReplicas }}
  maxReplicas: {{ .Values.hpa.sensorSimulator.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.sensorSimulator.targetCPUUtilizationPercentage }}
