apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices.fullname" . }}-sensor-simulator
spec:
  replicas: {{ .Values.sensorSimulator.replicaCount }}
  selector:
    matchLabels:
      app: sensor-simulator
  template:
    metadata:
      labels:
        app: sensor-simulator
    spec:
      containers:
        - name: sensor-simulator
          image: "{{ .Values.sensorSimulator.image.repository }}:{{ .Values.sensorSimulator.image.tag }}"
          ports:
            - containerPort: {{ .Values.sensorSimulator.env.SERVER_PORT }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.sensorSimulator.env.SERVER_PORT }}"
            - name: SENSOR_SIMULATOR_ENDPOINT
              value: "{{ .Values.sensorSimulator.env.SENSOR_SIMULATOR_ENDPOINT }}"
