apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-sensor-simulator
spec:
  type: {{ .Values.sensorSimulator.service.type }}
  ports:
    - port: {{ .Values.sensorSimulator.service.port }}
      targetPort: {{ .Values.sensorSimulator.env.SERVER_PORT }}
      protocol: TCP
      name: http
  selector:
    app: sensor-simulator
