apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices.fullname" . }}-task-orchestrator
spec:
  replicas: {{ .Values.taskOrchestrator.replicaCount }}
  selector:
    matchLabels:
      app: task-orchestrator
  template:
    metadata:
      labels:
        app: task-orchestrator
    spec:
      containers:
        - name: task-orchestrator
          image: "{{ .Values.taskOrchestrator.image.repository }}:{{ .Values.taskOrchestrator.image.tag }}"
          ports:
            - containerPort: {{ .Values.taskOrchestrator.env.SERVER_PORT }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.taskOrchestrator.env.SERVER_PORT }}"
            - name: KEYCLOAK_ISSUER_URI
              value: "http://{{ .Values.global.hostIP }}:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}"
            - name: KEYCLOAK_JWK_SET_URI
              value: "http://{{ .Values.global.hostIP }}:{{ .Values.global.keycloak.port }}/realms/{{ .Values.global.keycloak.realm }}/protocol/openid-connect/certs"
            - name: KEYCLOAK_CLIENT_ID
              value: "{{ .Values.global.keycloak.clientId }}"
            - name: KEYCLOAK_PROVIDER
              value: "{{ .Values.taskOrchestrator.env.KEYCLOAK_PROVIDER }}"
            - name: CORS_ALLOWED_ORIGINS
              value: "{{ .Values.taskOrchestrator.env.CORS_ALLOWED_ORIGINS }}"
            - name: KAFKA_HOST
              value: "{{ .Values.global.hostIP }}"
            - name: KAFKA_PORT
              value: "{{ .Values.global.kafka.port }}"
            - name: KAFKA_TASK_REG_TOPIC
              value: "{{ .Values.global.kafka.taskTopic }}"
            - name: MONGO_HOST
              value: "{{ .Values.global.hostIP }}"
            - name: MONGO_PORT
              value: "{{ .Values.global.mongo.port }}"
            - name: MONGO_USERNAME
              value: "{{ .Values.global.mongo.username }}"
            - name: MONGO_PASSWORD
              value: "{{ .Values.global.mongo.password }}"
