global:
  hostIp: "10.49.148.80"
  replicaCount: 1
  imagePullPolicy: IfNotPresent

db:
  host: "{{ .Values.global.hostIp }}"
  port: "5432"
  name: mydatabase
  user: myuser
  pass: mypassword

rabbitmq:
  host: "{{ .Values.global.hostIp }}"
  username: admin
  password: admin
  exchange: flexibility-bridge.exchange

dataApi:
  name: data-api
  image: sbhrwldocker/data-api
  tag: latest
  serverPort: 8085
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    cpuTarget: 50
    memoryTarget: 60

uiApp:
  name: ui-app
  image: sbhrwldocker/ui-app
  tag: latest
  port: 8080
  backendUrl: "http://fhs.local/api"

flexibilityHubSimulator:
  name: flexibility-hub-simulator
  image: sbhrwldocker/flexibility-hub-simulator
  tag: latest
  port: 8081
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    cpuTarget: 50
    memoryTarget: 60

flexibilityBridge:
  name: flexibility-bridge
  image: sbhrwldocker/flexibility-bridge
  tag: latest

protocolAdapter:
  name: protocol-adapter
  image: sbhrwldocker/protocol-adapter
  tag: latest

storageService:
  name: storage-service
  image: sbhrwldocker/storage-service
  tag: latest
  grpcPort: 9090

hesSimulator:
  name: hes-simulator
  image: sbhrwldocker/hes-simulator
  tag: latest

ingress:
  enabled: true
  host: fhs.local
  paths:
    uiApp: /ui(/|$)(.*)
    dataApi: /api(/|$)(.*)
    flexibilityHubSimulator: /simulator(/|$)(.*)
  tls: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2