spring:
  cloud:
    gcp:
      project-id: my-gcp-project-id
      pubsub:
        # leave this blank in production
        emulator-host: ""
messaging:
  pubsub:
    request-topic: flexibility-hub.request
    request-subscription: flexibility-hub.request-sub
    response-topic: flexibility-hub.response
    response-subscription: flexibility-hub.response-sub


