version: "3.9"

services:
  secured-endpoint:
    build: .
    image: secured-endpoint:local
    container_name: secured-endpoint
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      KEYCLOAK_URL: http://10.158.22.221:8080/realms/master
    extra_hosts:
      - "localhost:10.158.22.221"