command:
  name: command-orchestration
  replicas: 3
  image: sbhrwldocker/command-orchestration:prod
  containerPort: 9081
  servicePort: 8081
  nodePort: 32081

task:
  name: task-orchestration
  replicas: 3
  image: sbhrwldocker/task-orchestration:prod
  containerPort: 9082
  servicePort: 8082
  nodePort: 32082

env:
  MONGO_HOST: prod-db.internal
  MONGO_PORT: "27017"
  SPRING_DATA_MONGODB_USERNAME: root
  SPRING_DATA_MONGODB_PASSWORD: root123
  SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
  SPRING_DATA_MONGODB_DATABASE: commandorchestrator
  KAFKA_BOOTSTRAP_SERVERS: prod-kafka:29092
