apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.task.name }}-deployment
spec:
  replicas: {{ .Values.task.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.task.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.task.name }}
    spec:
      containers:
        - name: {{ .Values.task.name }}
          image: {{ .Values.task.image }}
          ports:
            - containerPort: {{ .Values.task.containerPort }}
          env:
            - name: MONGO_HOST
              value: {{ .Values.env.MONGO_HOST }}
            - name: MONGO_PORT
              value: "{{ .Values.env.MONGO_PORT }}"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: {{ .Values.env.SPRING_DATA_MONGODB_USERNAME }}
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: {{ .Values.env.SPRING_DATA_MONGODB_PASSWORD }}
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: {{ .Values.env.SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE }}
            - name: SPRING_DATA_MONGODB_DATABASE
              value: {{ .Values.env.SPRING_DATA_MONGODB_DATABASE }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}
            - name: SERVER_PORT
              value: "{{ .Values.task.containerPort }}"
