apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.command.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.command.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.command.servicePort }}
      targetPort: {{ .Values.command.containerPort }}
      nodePort: {{ .Values.command.nodePort }}
