apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dataApi.name }}-service
  labels:
    app: {{ .Values.dataApi.name }}
spec:
  type: NodePort 
  selector:
    app: {{ .Values.dataApi.name }}
  ports:
    - port: {{ .Values.dataApi.serverPort }}
      targetPort: {{ .Values.dataApi.serverPort }}
      protocol: TCP
      nodePort: {{ .Values.dataApi.nodePort }}