apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flexibilityHubSimulator.name }}-service
  labels:
    app: {{ .Values.flexibilityHubSimulator.name }}
spec:
  type: NodePort 
  selector:
    app: {{ .Values.flexibilityHubSimulator.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.flexibilityHubSimulator.port }}
      targetPort: {{ .Values.flexibilityHubSimulator.port }}
      nodePort: {{ .Values.flexibilityHubSimulator.nodePort }}