apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.postgres.stateStoreName }}
  namespace: default
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: |
        host={{ .Values.postgres.host }}
        port={{ .Values.postgres.port }}
        user={{ .Values.postgres.username }}
        password={{ .Values.postgres.password }}
        database={{ .Values.postgres.database }}
        sslmode=disable
    - name: maxOpenConns
      value: "20"
    - name: maxIdleConns
      value: "5"
    - name: idleTimeout
      value: "30s"
