apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.rabbitmq.pubsubName }}
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "{{ .Values.rabbitmq.connectionString }}"
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: requeueInFailure
      value: "true"
    - name: prefetchCount
      value: "10"
    - name: exclusive
      value: "false"
