apiVersion: v1
kind: Service
metadata:
  name: {{ include "flexibility-hub-simulator.serviceName" . }}
  labels:
    app: {{ include "flexibility-hub-simulator.serviceName" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.services.flexibilityHubSimulator.port }}
      targetPort: {{ .Values.services.flexibilityHubSimulator.port }}
      nodePort: {{ .Values.services.flexibilityHubSimulator.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.services.flexibilityHubSimulator.name }}
