apiVersion: v1
kind: Service
metadata:
  name: {{ include "flexibilityHubSimulator.name" . }}-service
  labels:
    app: {{ include "flexibilityHubSimulator.name" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "flexibilityHubSimulator.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.flexibilityHubSimulator.port }}
      targetPort: {{ .Values.services.flexibilityHubSimulator.port }}
      nodePort: {{ .Values.services.flexibilityHubSimulator.nodePort }}
