apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.flexibilityHubSimulator.name }}-service
  labels:
    app: {{ .Values.services.flexibilityHubSimulator.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.services.flexibilityHubSimulator.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.flexibilityHubSimulator.port }}
      targetPort: {{ .Values.services.flexibilityHubSimulator.port }}
      nodePort: {{ .Values.services.flexibilityHubSimulator.nodePort | default 30881 }}
