apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.flexibilityBridge.name }}
  labels:
    app: {{ .Values.services.flexibilityBridge.name }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.services.flexibilityBridge.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.flexibilityBridge.name }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{ .Values.services.flexibilityBridge.name }}"
        dapr.io/app-port: "{{ .Values.services.flexibilityBridge.port }}"
        dapr.io/pubsub-name: "{{ .Values.rabbitmq.pubsubName }}"
        dapr.io/components-path: "{{ .Values.global.daprComponentsPath }}"
    spec:
      containers:
        - name: {{ .Values.services.flexibilityBridge.name }}
          image: "{{ .Values.services.flexibilityBridge.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.flexibilityBridge.port }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.services.flexibilityBridge.port }}"
            - name: DAPR_PUBSUB_NAME
              value: "{{ .Values.rabbitmq.pubsubName }}"
            - name: DAPR_HUB_REQUEST_TOPIC
              value: "{{ .Values.services.flexibilityBridge.hubRequestTopic }}"
            - name: DAPR_CONNECTOR_REQUEST_TOPIC
              value: "{{ .Values.services.flexibilityBridge.connectorRequestTopic }}"
            - name: DAPR_CONNECTOR_RESPONSE_TOPIC
              value: "{{ .Values.services.flexibilityBridge.connectorResponseTopic }}"
            - name: DAPR_HUB_RESPONSE_TOPIC
              value: "{{ .Values.services.flexibilityBridge.hubResponseTopic }}"
            - name: STORAGE_SERVICE_HOST
              value: "{{ .Values.services.storageService.name }}"
            - name: STORAGE_SERVICE_PORT
              value: "{{ .Values.services.storageService.grpcPort }}"
