apiVersion: v1
kind: Service
metadata:
  name: {{ include "storageService.name" . }}-service
  labels:
    app: {{ include "storageService.name" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "storageService.name" . }}
  ports:
    - name: http
      port: {{ .Values.services.storageService.httpPort }}
      targetPort: {{ .Values.services.storageService.httpPort }}
      nodePort: {{ .Values.services.storageService.nodePort }}
    - name: grpc
      port: {{ .Values.services.storageService.grpcPort }}
      targetPort: {{ .Values.services.storageService.grpcPort }}
