# Server port
server.port=8080
# JSON payload
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.mvc.json.prefix=/api
spring.mvc.json.suffix=.json

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=command-orchestrator-group
spring.kafka.consumer.auto-offset-reset=earliest

# Kafka Producer Configuration
spring.kafka.producer.topic=task.requested

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=commandorchestrator
spring.data.mongodb.username=root
spring.data.mongodb.password=root123
spring.data.mongodb.authentication-database=admin

# Logging configuration
logging.level.root=INFO
logging.level.com.example.postservice=DEBUG